name: Deploy to AKS on Image Update

on:
  push:
    paths:
      - 'latestImageTag.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: '2.0.80'

    - name: Log in to Azure
      run: az login --service-principal ${{ secrets.AZURE_SP_APP_ID }} --tenant ${{ secrets.AZURE_SP_TENANT_ID }} --password ${{ secrets.AZURE_SP_SECRET }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group rg-test --name tatatech

    - name: Read image name from file
      id: read-image
      run: echo "::set-output name=image::$(cat latestImageTag.txt)"

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/my-go-app shiveshabhishek/go-welcome-app:${{ steps.read-image.outputs.image }}

